name: Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  playwright:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: test
    defaults:
      run:
        working-directory: Playwright
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
        env:
          LOGIN_PAGE: ${{ vars.LOGIN_PAGE }}
          USERNAME: ${{ vars.USERNAME }}
          PASSWORD: ${{ vars.PASSWORD }}
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: Playwright/playwright-report/
          retention-days: 30

  cypress:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: test
    defaults:
      run:
        working-directory: Cypress
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install
      - name: Install Cypress binary
        run: npx cypress install
      - name: Run Cypress tests
        run: npx cypress run
        env:
          LOGIN_PAGE: ${{ vars.LOGIN_PAGE }}
          SAUCE_USERNAME: ${{ vars.SAUCE_USERNAME }}
          SAUCE_PASSWORD: ${{ vars.SAUCE_PASSWORD }}
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: cypress-report
          path: Cypress/cypress/screenshots/
          retention-days: 30